### ISSUE TITLE
The 'name' attr in MAPS objects had side effects

### ISSUE THREAD

**Issue by peter5he1by** [sh4rkman/SquadCalc#142]
Hey, sh4rkman.

Before the heightmap function updated, the only thing used to find the map file path is the `mapURL` attribute in `MAPS` object array.

And I was translating this project and sharing with players in my country without any masquerading, just by modifying the `name` attribute.

But now the way to find heightmap path is affecting by the `name` attribute. Is there any way to optimize this for internationalization?

I think adding an attribute like 'id' for inner use is better.

Thanks for your work and love, again. This project is awesome.

**Comment by sh4rkman** [comment]
Hi !

I can see the problem, would it work for you if i rename every heightmap files `"heightmap.webp"` and change the way i load them by replacing : 

`new squadHeightmap("maps"+ map.mapURL + map.name.toLowerCase() + ".webp", imageBounds, this)`

with : 

`new squadHeightmap("maps"+ map.mapURL + "heightmap.webp", imageBounds, this)`

That way you can continue to edit maps.js with chineses map name without breaking the mecanic.

**Comment by sh4rkman** [comment]
That being said, i'll need to do some proper internalization one day. Probably in the next months.

**Comment by sh4rkman** [comment]
fixed with bfff285f4e18f941cea8ec26b0d2ee3beb4cba86

**Comment by sh4rkman** [comment]
FYI squadcalc will be fully translated in a few days and support regular i18n translations with json files.
Feel free to switch to the main branch and provide translation if mine are weird

![image](https://github.com/user-attachments/assets/7ede8316-b7ce-4ce0-8aec-a31e77f27761)

![image](https://github.com/user-attachments/assets/55831dcf-5f88-4dca-b4a0-1f0e2901e9cc)

![image](https://github.com/user-attachments/assets/1f345ef6-f781-4b80-99b5-4dda6955819b)
