### ISSUE TITLE
The results from the mortar calculator are inaccurate.

### ISSUE THREAD

**Issue by SuisQi** [sh4rkman/SquadCalc#155]
After the 8.0 update, I tested the mortar and found that the calculated mils deviated by more than 100 meters from the actual location. Did this update also change the parameters for mortars? I used the XYZ calculator and got the same result.

**Comment by sh4rkman** [comment]
Hi there,

1. Are we talking about default mortars or other weapon (ub, grad, 120mm?)

2. On witch specific map did you encounter this

3. Can you provide an actual situation that you observed it (weapon +target position), i'll test it

**Comment by SuisQi** [comment]
![image](https://github.com/sh4rkman/SquadCalc/assets/160198334/23512203-024e-4bb0-84bd-e7ec9861541d)
In reality, the mortar shell landed at the location indicated by my red arrow.

**Comment by sh4rkman** [comment]
Will test it tonight.

**Comment by SuisQi** [comment]
I apologize for the potential error in adjusting the mils, which caused such a significant deviation. However, when comparing this calculator to the XYZ calculator using the same scenario, the XYZ calculator gives a mil value of 1060, while this one gives 1055. The correct value is 1060. I checked the code, and both calculators use the same formula, but I haven't examined the details thoroughly.

**Comment by sh4rkman** [comment]
You were shooting at 1155 instead of 1055 right ? 😄

Since you mentionned imprecision, i'll confront 1055 vs 1060 tonight and will post results here

**Comment by sh4rkman** [comment]
You were right ! Yehorivka heightmap was _slightly_ misaligned resulting in a few meters difference in this exact scenario.
When re-aligning scrupulously the heightmap squadcalc now gives.. 1059.3

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/bdc7971d-6d25-4ea4-b482-5e1215beaf95)
![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/21ab80c3-c4e1-4911-8537-360ec872780c)

Will push a fix soon, thanks a lot !
