### ISSUE TITLE
Technical mortar is not accurate

### ISSUE THREAD

**Issue by frontlinehq** [sh4rkman/SquadCalc#159]
Hello, 

I would like to report a bug. Techincal mortar calculator is not accurate. It's showing underestimated values for distances. For example: Elevation is 69.2 degrees but in reality it should be 64.2. Tested many times with another calculator and it's seems to be a bug.

**Comment by sh4rkman** [comment]
Yes ! There is a flat 5° difference because of an ingame error in the squad HUD.

I had a flat -5deg applied to results until now but removed it by mistake : will fix it tonight
