### ISSUE TITLE
Add projectile height apex on click

### ISSUE THREAD

**Issue by Ferrariic** [sh4rkman/SquadCalc#163]
Situation: The height barrier/skybox prevents some projectiles from reaching their intended destination.

Solution: Adding a height readout as described below, only on projectile examination click, this would allow users to determine valid targets based upon skybox height.

![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/d1ff19f3-bf5d-46b5-bbd4-02bc4eab2668)

Example: As recently discovered and referred in issue #148, the MK19 and other projectiles may have a more limited maximum ranged depending upon the map used by virtue of colliding with the skybox. 

Example: Valid target on move
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/b8a6c6b1-7b30-49ab-a918-107de8ce595c)
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/7c72e834-6d0f-4a87-9834-4ab615e3027f)

Example: Invalid target at kropy, the other 1 star.
![image](https://github.com/sh4rkman/SquadCalc/assets/5789682/f1a33bb7-c5bf-40ad-8d73-a188404e02c7)

Benefits: This may allow for the mk19 to find true max ranges on each map, as the sky is the limit (literally). This would allow for additional future high velocity indirect fire projectiles to see their potential max range as well.

**Comment by sh4rkman** [comment]
Hm.. this is definitly not a skybox problem since weapons shooting at high angles (45-90°) can reach up to 1km high 

110 velocity + 85° angle = 613m max height (classic mortars)
142 velocity + 85° angle = 1021m high (M121)
240 velocity + 210 angle = 378m high (your MK19 example)

**Comment by Ferrariic** [comment]
> Hm.. this is definitly not a skybox problem since weapons shooting at high angles (45-90°) can reach up to 1km high
> 
> 110 velocity + 85° angle = 613m max height (classic mortars) 142 velocity + 85° angle = 1021m high (M121) 240 velocity + 210 angle = 378m high (your MK19 example)

Tyvm for looking into this, let me retest some things.

**Comment by Ferrariic** [comment]
Okay, I was wrong. It seems like after **19s** of flight time the projectile disappears. It puts the max range at ~4.2km in game practically. The limitation would be with projectile time, not vertical height. Feel free to close this issue, I will have to address this in #148 and #149.
