### ISSUE TITLE
Add the setting to show the high/low angle on the map

### ISSUE THREAD

**Issue by xMatador-Git** [sh4rkman/SquadCalc#164]
Not sure if it was removed,bugged, or ever existed, but based on the image in the readme I thought the setting would be somewhere, but couldn't find it
![image](https://github.com/sh4rkman/SquadCalc/assets/57844715/28967dd5-874c-496e-ad35-195f902e7942)

**Comment by sh4rkman** [comment]
Testable right now at https://dev.squadcalc.app/

![Uploading image.png…]()
