### ISSUE TITLE
Add Custom weapon implementation 

### ISSUE THREAD

**Issue by Ferrariic** [sh4rkman/SquadCalc#168]
Goal: users would be able to click on the weapon drop down and click "Add New Weapon", this would pull up a "Build weapon" menu where they could select velocity, Moa, if vehicle or not, etc, and implement custom weapons into squad calc. 

This would be beneficial for modders, as well as vanilla players experimenting with weapons in game. 

This issue would remove #148, and #149 which look for mk19 implementation and instead replace it with a customizable solver.

**Comment by sh4rkman** [comment]
Not exactly what you wanted, but we can know introduce "experimental" weapons that can be toggled on/off (off by default) in the settings. That way the default player won't see it until he check it knowing it should be use at his own risk.

If anyone want to introduce some weird shit, it's possible under this category "experimental"
