### ISSUE TITLE
Adding Custom Maps

### ISSUE THREAD

**Issue by Svdovych** [sh4rkman/SquadCalc#170]
I'm interested in using a local instance of the calculator on custom maps and curious what you are using to make all the image files you have for regular maps. Would you share the tool/process and perhaps a short guide on how to do that?

**Comment by sh4rkman** [comment]
Hi ! I use a sliiightly modified process of endebert guide to add news maps on squadmc

https://github.com/Endebert/squadmc-maps/wiki/How-to-add-new-maps-to-SquadMC

Basically the same but in .webp
