### ISSUE TITLE
Add for multi-language support

### ISSUE THREAD

**Issue by GoldBro233** [sh4rkman/SquadCalc#174]
As stated in the title, I hope to add support for multiple languages and include a language switch feature.
If this can be done, I would be very grateful.

**Comment by sh4rkman** [comment]
Working on it ! I was too lazy for it but i did take another look at i18 and it actually not that hard.

![20240714_00h51m_iPrPWrVCStm](https://github.com/user-attachments/assets/10e1a62a-b7cf-4611-b4be-1f172047b6b2)

**Comment by sh4rkman** [comment]
WIP (translations are from chat gpt and can be weird) 

![image](https://github.com/user-attachments/assets/588a775c-055b-4507-b0c4-6d8cc93c11c1)

![image](https://github.com/user-attachments/assets/aa8203df-fdc3-420c-8214-e992e0ab09b0)

![image](https://github.com/user-attachments/assets/a61bd872-6967-45a0-bf30-a2f738965dee)
