### ISSUE TITLE
120mm deprecated

### ISSUE THREAD

**Issue by TheGrimReaper13** [sh4rkman/SquadCalc#176]
120mm mortar range was reduced to 2000m while the calc still shows a max range of 3600m which will make all calculations invalid.
PS: It's really great how this project has progressed :D

**Comment by sh4rkman** [comment]
Hi ! Thank you !

The nerfed velocity has been updated for a while now, i think you are still using a previous cached version of squadcalc.
Refreshing the page should load the correct current version (28.0.0)

![image](https://github.com/user-attachments/assets/1558d264-a559-48b9-b525-4dd66b75b814)
