### ISSUE TITLE
Real maptexture in game

### ISSUE THREAD

**Issue by zfzr031** [sh4rkman/SquadCalc#206]
no map flash bomb by goosebay (

https://github.com/zfzr031/maps/raw/refs/heads/main/GooseBaymap.HDR
https://github.com/zfzr031/maps/raw/refs/heads/main/kokanmap.HDR
https://github.com/zfzr031/maps/raw/refs/heads/main/foolsroad.HDR

**Comment by sh4rkman** [comment]
Hi,

Can you provide some more description ? is it a problem with squadcalc basemap ?
I'm currently using raw map from SDK compressed in `.webp`, maybe compression is losing some colors intensity ?

**Comment by zfzr031** [comment]
> Hi,
> 
> Can you provide some more description ? is it a problem with squadcalc basemap ? I'm currently using raw map from SDK compressed in `.webp`, maybe compression is losing some colors intensity ?

The image you exported does not have the effect seen in the game. 
I created a new camera on the SDK and exported simulated in-game images - This will fix the issue where the current image looks inconsistent with the in-game image.

**Comment by sh4rkman** [comment]
Nice spot, i already saw in the past that they applied filters on minimap files directly with the SDK and that it wasn't exported when right clicking the minimap itself.

Will rework those 3 maps starting from your attached files next week.

Thanks !
