### ISSUE TITLE
Why is techmortar inaccurate? 

### ISSUE THREAD

**Issue by zoslcne** [sh4rkman/SquadCalc#227]
Why is techmortar not accurate? It can hit me from behind at this angle.
![IMG_20241126_104647524](https://github.com/user-attachments/assets/0df042f5-6951-439c-8ec2-5011e4de6be0)
![IMG_20241126_104741065](https://github.com/user-attachments/assets/94863b1b-2447-4ebc-9d36-23c545b422fd)
![IMG_20241126_104704747](https://github.com/user-attachments/assets/5fab593c-c770-4125-a6c5-8f5287f8f557)

**Comment by sh4rkman** [comment]
The calculations are "correct" but it doesn't take into account the fact that the weapon is bugged ingame.  I had a fix for this but looks like it doesn't work.
