### ISSUE TITLE
Weird String

### ISSUE THREAD

**Issue by TheGrimReaper13** [sh4rkman/SquadCalc#63]
**Describe the bug**
Weird string added when saving firing solution with MLRS and Mortar Technical. No issue when using any of the other weapons.

**To Reproduce**
1. Create a valid firing solution with the MLRS and Mortar Technical.
2. Save that firing solution.
3. Nonsense characters get added to the end of the saved entry.

**Screenshots**

![weird string](https://user-images.githubusercontent.com/58264881/226118688-5f31935b-dfe4-4179-acb5-3ea214d12559.PNG)

**Desktop:**
 - Firefox
 - Version 110.0

**Comment by sh4rkman** [comment]
Thanks ! Fixed for now, will deploy this evening
