### ISSUE TITLE
MLRS: Support for angles larger than 45°

### ISSUE THREAD

**Issue by TheGrimReaper13** [sh4rkman/SquadCalc#65]
It's in the title. It can be more useful to use the higher angle to hit some targets behind buildings or similar.

**Comment by sh4rkman** [comment]
Perfectly doable : i'm already calculating high & low angle
But this means i need to either make a new button to let the user choose low/high, or display both

I'll look into into if i can find a UI solution

**Comment by TheGrimReaper13** [comment]
Doing it similar to the 120mm should work well enough.

**Comment by sh4rkman** [comment]
Yeah looks like the ideal way.

But i'm confused, the ingame table shows angle >45° only for 1650-1500m, can you go higher? Like 80° ?

**Comment by TheGrimReaper13** [comment]
On level ground it only goes up something a bit above 55°. If you angle the vehicle you can achieve much higher angles.
The calculator would already be great if the high angles down to 1500m can be used.

**Comment by Sunstealer1** [comment]
Is this feature still being worked on? I very interested in seeing this feature developed. I have seen this "high angle" feature implemented for the rocket techie (UB-32) in an old calculator I grabbed from a Reddit [comment](https://www.reddit.com/r/joinsquad/comments/bt8iyy/comment/ep7zcm0/?utm_source=share&utm_medium=web2x&context=3). It still works accurately for squad V6.0.1 (post ICO). I mainly use it to completely avoid obstacles in the line of fire by angling the techie on a hill and firing at a high angle over trees etc.

**Comment by sh4rkman** [comment]
I kinda gave up the idea to find a elegant UI implementation, since i don't really find it usefull.
Again, the code is already there to calculate high&low, i just need to find a nice way to implement it.

Played a bit with the UI tonight and i think i found a elegant solution : 

![20231023_23h44m_iyiBQkxoc8A](https://github.com/sh4rkman/SquadCalc/assets/9033912/d484e3c2-23cb-4755-97b9-70a128f1d72d)

I'll work on it tomorrow

**Comment by Sunstealer1** [comment]
That looks nice!

Feel free to let me know if you need any testing done or if you need feedback on the UI

**Comment by sh4rkman** [comment]
I've setup https://dev.squadcalc.app for testing purpose.
You can play with it/test it ingame
