### ISSUE TITLE
GRAD range was changed in 4.4

### ISSUE THREAD

**Issue by TheGrimReaper13** [sh4rkman/SquadCalc#67]
Range now is between 1000-2050m.

**Comment by sh4rkman** [comment]
I didn't see it in the patchnotes, the ingame table changed ?

**Comment by TheGrimReaper13** [comment]
Yes it wasn't mentioned in patchnotes. But they changed it.

**Comment by sh4rkman** [comment]
fixed with 886483f559b1972db20556c360fec8666cad0dbf

Interesting, they removed something (air resistance ?) in the grad formula : i can now use the classic formula with a fixed velocity
