### ISSUE TITLE
Input skipping to target from weapon

### ISSUE THREAD

**Issue by TheGrimReaper13** [sh4rkman/SquadCalc#69]
After inputting first part of weapon it skips to end of target input string.
So after i.e writing "A01" it will set cursor to end of target input string.

Browser: Safari Desktop

Seems to work fine though in Firefox.

**Comment by sh4rkman** [comment]
Is it a new bug introduced recently or did you just happen to test it for the first with Safari ?

**Comment by sh4rkman** [comment]
fixed with bc9056b784bbf13d127c9d7b0ca6fde70c3058b5
