### ISSUE TITLE
Consider showing the theoretical distance to a target even when out of range

### ISSUE THREAD

**Issue by danieljancar** [sh4rkman/SquadCalc#86]
### Current
When entering a target which is too far away, we show a huge banner saying that. While this is obviously important I still think that showing the theoretical metrics (degrees and height) would be a benefit to a lot of experienced players.

### Why?
I had a few cases where my target was out of range for a few meters (≈25m-100m) while I still would've been able to hit very close to it or in the area around. I wanted to use the exact grid which I was ordered to shoot at, where the distance to the grid was out of range for a few meters, meaning I couldn't retrieve the needed metrics and needed to search for a nearby grid which was costing me time again.

### Solution
When a target is out of range still show the theoretical metrics to reach it or the closest possible ones, vice versa, making the banner saying that the target out of range a bit smaller to provide space for the theoretical distance/metrics to the targeted grid.

**Comment by sh4rkman** [comment]
Well, there is the problem : if the target is out of range, i don't have a elevation to display. 
Max distance is reached at 45° (around 800mil) and that's it.

**Comment by danieljancar** [comment]
I feel that would already be a good feature to add. 👍🏻

**Comment by sh4rkman** [comment]
Already doing it !

![image](https://github.com/sh4rkman/SquadCalc/assets/9033912/9b9dee35-a902-478f-8bd4-c05acce312e3)
